alias cd.. "cd .."
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias ......="cd ../../../../../"
alias .......="cd ../../../../../../"
alias ........="cd ../../../../../../../"
alias lf="ls -ld */"
alias c "cat"
alias cd.. "cd .."
alias a "awk"
alias e.="e ."
alias f "find . -iname"
alias g="git"
alias gr "grep --no-messages"
alias n nvim
alias o "wsl-open"
alias sp "sudo pacman"
alias s "sudo"
alias se "sudoedit"
alias t "tail"
alias w "which"
alias wi "whereis"
alias x "xargs"
alias cx 'chmod +x'
alias 'c-x' 'chmod -x'

alias ga "git add"
alias gc "git commit -a"
alias gp "git pull"
alias gpu "git push"
alias gco "git checkout"
alias gdi "git diff"
alias gs "git status --short"
alias gl "git lg"
alias gd "git difftool"

alias h="head"
alias h-1="head -1"
alias h-2="head -2"
alias h-3="head -3"
alias h-4="head -4"
alias h-5="head -5"
alias h-6="head -6"
alias h-7="head -7"
alias h-8="head -8"
alias h-9="head -9"

alias ib "inv build"
alias ib "inv build.rebuild"

alias t="tail"
alias t-1="tail -1"
alias t-2="tail -2"
alias t-3="tail -3"
alias t-4="tail -4"
alias t-5="tail -5"
alias t-6="tail -6"
alias t-7="tail -7"
alias t-8="tail -8"
alias t-9="tail -9"

setenv EDITOR nvim
set fish_greeting
