alias a "awk"
alias cd.. "cd .."
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias ......="cd ../../../../../"
alias .......="cd ../../../../../../"
alias ........="cd ../../../../../../../"
alias lf="ls -ld */"
alias c "cat"
alias cd.. "cd .."
alias cx 'chmod +x'
alias 'c-x' 'chmod -x'
alias d "'/mnt/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/devenv.exe' /Edit"
alias e.="e ."
alias f "find . -iname"
alias g="git"
alias gr "grep -P --no-messages"
alias n nvim
alias n++="/mnt/c/Program\ Files\ \(x86\)/Notepad++/notepad++.exe"
alias o "wsl-open"
alias sp "sudo pacman"
alias s "sudo"
alias se "sudoedit"
alias t "tail"
alias w "which"
alias wi "whereis"
alias w-l="wc -l"
alias x 'xargs '
alias z 'fzf | tr "\n" "\0\n" | xclip'
alias rg 'rg -j1' #limits rg to one thread because of wsl bug

alias ga "git add"
alias gb "git rebase -s resolve"
alias gc "git commit -a"
alias gn "git diff --name-only"
alias gll "git pull"
alias gsh "git push"
alias go "git checkout"
alias go. "git checkout -- ."
alias gob "git checkout -b"
alias gcp "git cherry-pick"
alias gi "git diff"
alias gs "git status --short"
alias gl "git lg"
alias g2 "git lg -2"
alias g3 "git lg -3"
alias g4 "git lg -4"
alias g5 "git lg -5"
alias g6 "git lg -4"
alias g7 "git lg -4"
alias g8 "git lg -4"
alias g9 "git lg -4"
alias g10 "git lg -10"
alias g20 "git lg -20"
alias g50 "git lg -50"
alias g100 "git lg -100"
alias g200 "git lg -200"
alias gd "git difftool"
alias gwa "git worktree add"
alias gwr "git worktree remove"
alias grc "git rebase --continue"
alias gra "git rebase --abort"
alias grv "git  rev-parse --verify"

alias h="head"
alias h1="head -1"
alias h2="head -2"
alias h3="head -3"
alias h4="head -4"
alias h5="head -5"
alias h6="head -6"
alias h7="head -7"
alias h8="head -8"
alias h9="head -9"
alias h10="head -10"
alias h20="head -20"
alias h50="head -50"
alias h100="head -100"

alias i "inv build"
alias ib "inv build"
alias ir "inv build.rebuild"

alias t="tail"
alias t1="tail -1"
alias t2="tail -2"
alias t3="tail -3"
alias t4="tail -4"
alias t5="tail -5"
alias t6="tail -6"
alias t7="tail -7"
alias t8="tail -8"
alias t9="tail -9"
alias t10="tail -10"
alias t20="tail -20"
alias t50="tail -50"
alias t100="tail -100"

alias map 'xargs -n1'

setenv EDITOR nvim
set fish_greeting
